import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ocym kuzhimattom",
  description: "Generated by create next app",
  viewport: 'width=device-width, initial-scale=1',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <nav className="p-4 bg-black text-white">
          <div className="max-w-full sm:max-w-6xl mx-auto flex flex-col sm:flex-row items-center sm:justify-between gap-4">
            <h1 className="text-lg sm:text-xl font-semibold">St. George OCYM Kuzhimattom</h1>
            <div className="flex flex-col sm:flex-row items-center gap-3">
              <a href="/" className="block px-2 py-1 hover:underline">Home</a>
              <a href="/knowus" className="block px-2 py-1 hover:underline">Know Us</a>
              <a href="/events" className="block px-2 py-1 hover:underline">Events</a>
              <a href="/contact" className="block px-2 py-1 hover:underline">Contact</a>
            </div>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
